version: 0.2
 
env:
  variables:
     #AWS_ACCESS_KEY_ID: ""
     #AWS_SECRET_ACCESS_KEY: ""
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - npm install --no-package-lock
      - npm install serverless -g
      # - command
  pre_build:
    commands:
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      # - command
      # - command
  build:
    commands:
      - npm run deploy:lambda:$ENVIRONMENT
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths